apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incident-responder-binding
  labels:
    purpose: incident-response
    temporary: "true"
subjects:
  - kind: User
    name: oncall@example.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: incident-responder
  apiGroup: rbac.authorization.k8s.io
